#!/usr/bin/env python3
# =============================================================================
# Wazuh → GitLab Issues Integration
# Triggers: severity > 15 (CRITICAL)
# Deploy path (inside manager pod): /var/ossec/integrations/custom-gitlab.py
# =============================================================================

import sys
import json
import logging
import urllib.request
import urllib.error
from datetime import datetime, timezone

# ── Logging ──────────────────────────────────────────────────────────────────
LOG_FILE = "/var/ossec/logs/integrations.log"
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s [custom-gitlab] %(levelname)s %(message)s",
)
logger = logging.getLogger(__name__)

# ── GitLab configuration – edit these or export as env vars ──────────────────
GITLAB_URL        = "https://gitlab.example.com/"        # e.g. https://gitlab.com
GITLAB_TOKEN      = "iserveu-Tjsguwqod-owu29YDhwuw"         # Project / personal access token
GITLAB_PROJECT_ID = "2379"                                 # numeric project id
SEVERITY_THRESHOLD = 8                                 # fire when level > this value

LABEL_MAP = {
    (16, 18): ["severity::critical", "wazuh", "security"],
    (19, 99): ["severity::critical", "wazuh", "security", "p1-urgent"],
}


def get_labels(level: int) -> list:
    for (lo, hi), labels in LABEL_MAP.items():
        if lo <= level <= hi:
            return labels
    return ["severity::critical", "wazuh", "security"]


def build_issue_body(alert: dict) -> str:
    rule      = alert.get("rule", {})
    agent     = alert.get("agent", {})
    data      = alert.get("data", {})
    timestamp = alert.get("timestamp", datetime.now(timezone.utc).isoformat())

    lines = [
        "## 🚨 Wazuh Critical Security Alert",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Alert ID**     | `{alert.get('id', 'N/A')}` |",
        f"| **Timestamp**    | `{timestamp}` |",
        f"| **Severity**     | `{rule.get('level', 'N/A')}` |",
        f"| **Rule ID**      | `{rule.get('id', 'N/A')}` |",
        f"| **Rule**         | {rule.get('description', 'N/A')} |",
        f"| **Agent ID**     | `{agent.get('id', 'N/A')}` |",
        f"| **Agent Name**   | `{agent.get('name', 'N/A')}` |",
        f"| **Agent IP**     | `{agent.get('ip', 'N/A')}` |",
        f"| **Groups**       | `{', '.join(rule.get('groups', []))}` |",
        f"| **MITRE ATT&CK** | `{', '.join(rule.get('mitre', {}).get('id', ['N/A']))}` |",
        "",
        "### Full Alert (JSON)",
        "```json",
        json.dumps(alert, indent=2),
        "```",
        "",
        "---",
        "*Auto-generated by Wazuh GitLab integration — do not edit header fields*",
    ]
    return "\n".join(lines)


def create_gitlab_issue(alert: dict):
    rule  = alert.get("rule", {})
    level = int(rule.get("level", 0))

    if level <= SEVERITY_THRESHOLD:
        logger.info("Alert level %d ≤ threshold %d — skipped", level, SEVERITY_THRESHOLD)
        return

    agent_name = alert.get("agent", {}).get("name", "unknown-agent")
    rule_desc  = rule.get("description", "Security Alert")
    title      = f"[CRITICAL-{level}] {rule_desc} on {agent_name}"
    body       = build_issue_body(alert)
    labels     = get_labels(level)

    payload = json.dumps({
        "title":       title,
        "description": body,
        "labels":      ", ".join(labels),
        "confidential": False,
    }).encode("utf-8")

    url = f"{GITLAB_URL}/api/v4/projects/{GITLAB_PROJECT_ID}/issues"
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "PRIVATE-TOKEN": GITLAB_TOKEN,
            "Content-Type":  "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode())
            logger.info("GitLab issue created: #%s  %s", result.get("iid"), result.get("web_url"))
    except urllib.error.HTTPError as exc:
        body_err = exc.read().decode()
        logger.error("GitLab HTTP %s: %s", exc.code, body_err)
        sys.exit(1)
    except Exception as exc:
        logger.error("GitLab request failed: %s", exc)
        sys.exit(1)


# ── Entry-point ───────────────────────────────────────────────────────────────
# Wazuh calls:  <script> <alert_file> <api_key_unused> <hook_url_unused>
if __name__ == "__main__":
    if len(sys.argv) < 2:
        logger.error("Usage: custom-gitlab.py <alert_json_file>")
        sys.exit(1)

    alert_file = sys.argv[1]
    try:
        with open(alert_file, "r") as fh:
            alert_data = json.load(fh)
    except Exception as exc:
        logger.error("Cannot read alert file %s: %s", alert_file, exc)
        sys.exit(1)

    logger.info("Processing alert id=%s level=%s",
                alert_data.get("id"), alert_data.get("rule", {}).get("level"))
    create_gitlab_issue(alert_data)
