apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: isiem-storage
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
parameters:
    archiveOnDelete: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
